# Generated by Django 4.1.7 on 2023-03-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecoponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ecoponto', models.URLField(max_length=100, unique=True)),
                ('estado', models.URLField(max_length=100)),
                ('regiao', models.URLField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.TextField(max_length=600)),
                ('endereco', models.TextField(max_length=600)),
                ('localizacao', models.TextField(max_length=600)),
                ('site', models.TextField(max_length=600)),
            ],
            options={
                'db_table': 'ecoponto',
                'managed': False,
            },
        ),
    ]
